"""
Django settings for monetate_recommendations_foo project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from __future__ import print_function

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

BACKEND_SERVER = ''  # US only backend services
BACKEND_SERVER_DSA = ''  # US only backend DSA services
BACKEND_SERVER_GLOBAL = ''  # Global backend services
BACKEND_SERVER_GLOBAL_DSA = ''  # Global backend DSA services
MONETATE_GEOIP_CITY_PATH = '/usr/share/GeoIP/GeoIPCity.dat'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monetate.system',
    'monetate.common',
    'monetate.user',
    'monetate.script',
    'monetate.retailer',
    'monetate.target',
    'monetate.campaign',
    'monetate.dataset',
    'monetate.test',
    'monetate.action',
    'monetate.content',
    'monetate.creative',
    'monetate.key',
    'monetate.location',
    'monetate.predictive_testing',
    'monetate.merch',
    'monetate.placement',
    'monetate.event',
    'monetate.segmentation',
    'monetate.audience',
    'monetate.idrec',
    'monetate.predicate',
    'monetate.reportv3',
    'monetate.adlink',
    'monetate.dio',
    'monetate.recs',
    'monetate_recommendations',
    'monetate.schema',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monetate_recommendations.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASE_ROUTERS = ['monetate.common.router.DefaultRouter']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'monetate_config',
        'HOST': 'localhost',
        'PORT': '',
        'USER': 'root',
        'PASSWORD': '',
        'TEST': {
            'CHARSET': 'utf8',
            'COLLATION': 'utf8_unicode_ci'
        },
    },
}


DEFAULT_WAREHOUSE_SCHEMA = 'public'  # replaces sqlalchemy_warehouse.DEFAULT_SCHEMA


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = False  # Monetate assumes naive datetime in naive_to_retailer


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# Import config management settings ####

try:
    from etc.recommendations_settings import *
except ImportError:
    print("Not importing etc.recs_settings", file=sys.stderr)
