@startuml precompute state diagram

[*] -[#black]-> PENDING : enqueue, attempts = 0

PENDING -[#green]-> PROCESSING : worker, attempts += 1

PROCESSING -[#green]-> PROCESSING : worker, heartbeat = now

PROCESSING -[#green]-> COMPLETE : worker
PROCESSING -[#green]-> RETRYABLE_FAILURE : worker, transient exception
PROCESSING -[#green]-> SYSTEM_ERROR : worker

PROCESSING -[#red]-> RETRYABLE_FAILURE: reaper, if heartbeat expired

RETRYABLE_FAILURE -[#red]-> PENDING : reaper, if attempts < max_tries
RETRYABLE_FAILURE -[#red]-> SYSTEM_ERROR : reaper, if attempts == max_tries

COMPLETE -[#black]-> [*]
SYSTEM_ERROR -[#black]-> [*]

@enduml
